runtime: aspnetcore
env: flex

env_variables:
  DB_CONNECTION: "Server=10.78.176.3;Port=5432;Database=codecomp;User ID=postgres;Password=codecompdb123;"
  SUPPORT_EMAIL: "support@codecomp.com"
  SMTP_HOST: "smtp.gmail.com"
  FROM_ADDRESS: "a@codecomp.com"
  FROM_PASSWORD: "password"
  SENDGRID_API_KEY: "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"
  ASPNETCORE_ENVIRONMENT: Development

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
